### ISSUE TITLE
problem running the program

### ISSUE THREAD

**Issue by sudomakeinstall2** [dreignier/cg-brutaltester#29]
I have a problem with cg-brutaltester. I have built the project both locally and using docker. But when I try to run it I get this error

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil
        at org.apache.logging.log4j.jcl.LogAdapter.getContext(LogAdapter.java:39)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
        at org.apache.logging.log4j.jcl.LogFactoryImpl.getInstance(LogFactoryImpl.java:40)
        at org.apache.logging.log4j.jcl.LogFactoryImpl.getInstance(LogFactoryImpl.java:55)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
        at com.magusgeek.brutaltester.Main.<clinit>(Main.java:16)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.ReflectionUtil
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 6 more
```

**Comment by fpringle** [comment]
Bump - I'm getting the same error!

**Comment by dreignier** [comment]
This issue appeared after a PR created by a github bot. It bumped log4j2 to a newer version. But brutaltester does not works with this version. I'll just revert the PR and use the previous version.

**Comment by Akadine** [comment]
I am having the same issue.
Removing the dependency did not help.
I am using this command, all my executables are in the target folder made by maven when I built brutal tester.
java -jar cg-brutaltester.jar -r "./csbref.exe" -p1 "./MadPodRacersGA.exe" -p2 "./MadPodRacersSearch.exe" -t 2 -n 100
