### ISSUE TITLE
Bunch of errors when testing with SpringChallenge 2021 ref (java 16.0.1 on windows 10)

### ISSUE THREAD

**Issue by NoRabbit** [dreignier/cg-brutaltester#33]
I tried a couple of different things but didn't put my hands into the code (yet). I took the released jars on github and also tried with a local compiled version. Same thing.
I just hope someone knows what this is about by just looking at those lines (I'm not familiar with java).
Thx.

22:33:21,063 ERROR [com.magusgeek.brutaltester.GameThread] Problem with referee output in game1. Output content:WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
null
null

22:33:21,064 ERROR [com.magusgeek.brutaltester.GameThread] Error during game 1
22:33:21,065 ERROR [com.magusgeek.brutaltester.GameThread] Exception in thread "Thread-0" java.lang.ExceptionInInitializerError
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
        at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.<init>(ProviderMethod.java:256)
        at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:71)
        at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275)
        at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
        at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.codingame.gameengine.core.RefereeMain.start(RefereeMain.java:62)
        at com.codingame.gameengine.runner.RefereeAgent$1.run(RefereeAgent.java:68)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @60285225
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
        ... 21 more
java.lang.RuntimeException: Invalid Referee command:
        at com.codingame.gameengine.runner.GameRunner.readCommand(GameRunner.java:318)
        at com.codingame.gameengine.runner.GameRunner.readGameInfo(GameRunner.java:302)
        at com.codingame.gameengine.runner.GameRunner.runAgents(GameRunner.java:127)
        at com.codingame.gameengine.runner.GameRunner.runGame(GameRunner.java:453)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at com.codingame.game.CommandLineInterface.main(CommandLineInterface.java:68)

**Comment by capgreen** [comment]
I have got same problem under Windows 10.

**Comment by dreignier** [comment]
Brutaltester does not support java 16.

In fact, I have never tester brutaltester on a Java higher than 1.8.
